### ISSUE TITLE
mac 开发脚手架出现 Error: spawn EACCES

### ISSUE THREAD

**Issue by styleyan** [styleyan/yxf-cli#2]
在MAC下会报以下错误问题
```js
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Command.executeSubCommand (/Users/yanxiaofei/myGithub/yxf-cli/node_modules/commander/index.js:562:14)
    at Command.parse (/Users/yanxiaofei/myGithub/yxf-cli/node_modules/commander/index.js:488:17)
    at Object.<anonymous> (/Users/yanxiaofei/myGithub/yxf-cli/bin/yxf:15:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by styleyan** [comment]
权限问题导致的，在该文件夹下运行`sudo chmod -R 777 bin`，即可
